import type { Meta, StoryObj } from '@storybook/react-vite';
import { expect } from 'storybook/test';
import ArticleList from './ArticleList';
import type { ArticleProps } from '../types/ArticleProps';

const sampleArticles: ArticleProps[] = [
  {
    id: 1,
    title: 'The Solar System',
    content: 'The Solar System is the gravitationally bound system of the Sun.',
  },
  {
    id: 2,
    title: 'Photosynthesis',
    content:
      'Photosynthesis is a process used by plants to convert light energy into chemical energy.',
    image: 'https://placehold.co/400x300/2d6a2e/ffffff?text=Plant',
  },
  {
    id: 3,
    title: 'Ocean Currents',
    content:
      'An ocean current is a continuous, directed movement of seawater generated by forces acting upon this water.',
  },
];

const meta = {
  component: ArticleList,
  tags: ['ai-generated'],
  parameters: {
    layout: 'centered',
  },
} satisfies Meta<typeof ArticleList>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    articles: sampleArticles,
  },
  play: async ({ canvas }) => {
    await expect(canvas.getByText('The Solar System')).toBeVisible();
    await expect(canvas.getByText('Photosynthesis')).toBeVisible();
    await expect(canvas.getByText('Ocean Currents')).toBeVisible();
  },
};

export const SingleArticle: Story = {
  args: {
    articles: [sampleArticles[0]],
  },
  play: async ({ canvas }) => {
    await expect(canvas.getByText('The Solar System')).toBeVisible();
    const list = canvas.getByRole('list');
    await expect(list).toBeVisible();
  },
};

export const EmptyList: Story = {
  args: {
    articles: [],
  },
  play: async ({ canvas }) => {
    const nav = canvas.getByRole('navigation', { name: /articles navigation/i });
    await expect(nav).toBeVisible();
  },
};
