import type { Meta, StoryObj } from '@storybook/react-vite';
import { expect, userEvent, within } from 'storybook/test';

import type { WikiArticle } from './components/WikiCard';

import App from './App';

const feedArticles: WikiArticle[] = [
  {
    title: 'Aurora',
    displaytitle: 'Aurora',
    extract:
      'Auroras are natural light displays that appear in the night sky near the polar regions.',
    pageid: 1001,
    url: 'https://en.wikipedia.org/wiki/Aurora',
    thumbnail: {
      source:
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      width: 1200,
      height: 800,
    },
  },
  {
    title: 'Bioluminescence',
    displaytitle: 'Bioluminescence',
    extract:
      'Bioluminescence is the production of light by living organisms such as plankton and fireflies.',
    pageid: 1002,
    url: 'https://en.wikipedia.org/wiki/Bioluminescence',
    thumbnail: {
      source:
        'https://images.unsplash.com/photo-1511300636408-a63a89df3482?auto=format&fit=crop&w=1200&q=80',
      width: 1200,
      height: 800,
    },
  },
];

const savedArticle: WikiArticle = {
  title: 'Ocean currents',
  displaytitle: 'Ocean currents',
  extract:
    'Ocean currents are continuous, directed movements of seawater generated by several forces.',
  pageid: 2001,
  url: 'https://en.wikipedia.org/wiki/Ocean_current',
  thumbnail: {
    source:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    width: 1200,
    height: 800,
  },
};

const meta = {
  title: 'AI Generated/Complex/App',
  component: App,
  parameters: {
    layout: 'fullscreen',
  },
} satisfies Meta<typeof App>;

export default meta;

type Story = StoryObj<typeof meta>;

export const DefaultFeed: Story = {
  loaders: [
    async () => {
      installAppMocks({
        likedArticles: [],
        articles: feedArticles,
      });
      return {};
    },
  ],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await expect(await canvas.findByText('Aurora')).toBeInTheDocument();
    await expect(canvas.getByRole('button', { name: 'About' })).toBeInTheDocument();
    await expect(canvas.getByRole('button', { name: 'Likes' })).toBeInTheDocument();
  },
};

export const LikesPanelOpen: Story = {
  loaders: [
    async () => {
      installAppMocks({
        likedArticles: [savedArticle],
        articles: feedArticles,
      });
      return {};
    },
  ],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await userEvent.click(canvas.getByRole('button', { name: 'Likes' }));
    await expect(await canvas.findByText('Liked Articles')).toBeInTheDocument();
    await expect(canvas.getByText('Ocean currents')).toBeInTheDocument();
  },
};

function installAppMocks({
  likedArticles,
  articles,
}: {
  likedArticles: WikiArticle[];
  articles: WikiArticle[];
}) {
  localStorage.setItem('lang', 'en');
  localStorage.setItem('likedArticles', JSON.stringify(likedArticles));
  window.fetch = createFetchMock(articles);
}

function createFetchMock(articles: WikiArticle[]): typeof fetch {
  return async (_input, _init) =>
    new Response(JSON.stringify(createWikipediaResponse(articles)), {
      headers: {
        'Content-Type': 'application/json',
      },
    });
}

function createWikipediaResponse(articles: WikiArticle[]) {
  return {
    query: {
      pages: Object.fromEntries(
        articles.map((article) => [
          String(article.pageid),
          {
            title: article.title,
            varianttitles: {
              en: article.displaytitle,
            },
            extract: article.extract,
            pageid: article.pageid,
            thumbnail: article.thumbnail,
            canonicalurl: article.url,
          },
        ]),
      ),
    },
  };
}
